spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
  pool:
    enabled: true
  liquibase:
    enabled: true
    change-log: "classpath:db/changelog.yaml"
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: 123456